services:
  - type: web
    name: face-crop-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python face_crop_api.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
